# Generated by Django 3.0.5 on 2021-05-23 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_link', models.URLField(validators=[django.core.validators.URLValidator])),
            ],
        ),
    ]
